name: Build/Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Debug GH_TOKEN (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: |
          if [ -z "$GH_TOKEN" ]; then
            echo "GH_TOKEN is NOT set!"
            exit 1
          else
            echo "GH_TOKEN is set correctly."
          fi
        shell: bash

      - name: Debug GH_TOKEN (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          if (-not $env:GH_TOKEN) {
            Write-Host "GH_TOKEN is NOT set!"
            exit 1
          } else {
            Write-Host "GH_TOKEN is set correctly."
          }
        shell: pwsh

      - name: Build projects
        run: npm run build

      - name: Build/Release Electron app (Linux - no snap)
        if: matrix.os == 'ubuntu-latest'
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          release: true
          args: --linux AppImage deb rpm --publish always
        env:
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true

      - name: Build/Release Electron app (Windows/macOS)
        if: matrix.os != 'ubuntu-latest'
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          release: true
          args: --publish always
        env:
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true
